// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Traffic.Infrastructure.Persistence;

#nullable disable

namespace Traffic.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TrafficDbContext))]
    [Migration("20260502192842_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Traffic.Infrastructure.Persistence.Entities.ExperimentRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Policy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("experiment_runs", (string)null);
                });

            modelBuilder.Entity("Traffic.Infrastructure.Persistence.Entities.SignalDecisionCommandEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("GreenDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("IntersectionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Policy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("SelectedSignalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("YellowDurationSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("RunId");

                    b.HasIndex("IntersectionId", "IssuedAtUtc");

                    b.ToTable("signal_decision_commands", (string)null);
                });

            modelBuilder.Entity("Traffic.Infrastructure.Persistence.Entities.SignalStateItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ElapsedSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("QueueLength")
                        .HasColumnType("integer");

                    b.Property<string>("SignalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("signal_state_items", (string)null);
                });

            modelBuilder.Entity("Traffic.Infrastructure.Persistence.Entities.SignalStateSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IntersectionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("RunId");

                    b.HasIndex("IntersectionId", "CapturedAtUtc");

                    b.ToTable("signal_state_snapshots", (string)null);
                });

            modelBuilder.Entity("Traffic.Infrastructure.Persistence.Entities.TrafficMeasurementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Arrivals")
                        .HasColumnType("integer");

                    b.Property<int>("Departures")
                        .HasColumnType("integer");

                    b.Property<string>("IntersectionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("MeasuredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("QueueLength")
                        .HasColumnType("integer");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("SignalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("RunId");

                    b.HasIndex("IntersectionId", "SignalId", "MeasuredAtUtc");

                    b.ToTable("traffic_measurements", (string)null);
                });

            modelBuilder.Entity("Traffic.Infrastructure.Persistence.Entities.SignalStateItemEntity", b =>
                {
                    b.HasOne("Traffic.Infrastructure.Persistence.Entities.SignalStateSnapshotEntity", "Snapshot")
                        .WithMany("Signals")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Traffic.Infrastructure.Persistence.Entities.SignalStateSnapshotEntity", b =>
                {
                    b.Navigation("Signals");
                });
#pragma warning restore 612, 618
        }
    }
}
