// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Traffic.Infrastructure.Persistence;

#nullable disable

namespace Traffic.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TrafficDbContext))]
    [Migration("20260502212009_AddSignalDecisionCommandPhaseFields")]
    partial class AddSignalDecisionCommandPhaseFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Traffic.Infrastructure.Persistence.Entities.ExperimentRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at_utc");

                    b.Property<string>("Policy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("policy");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("scenario");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("experiment_runs", (string)null);
                });

            modelBuilder.Entity("Traffic.Infrastructure.Persistence.Entities.SignalDecisionCommandEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("GreenDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("green_duration_seconds");

                    b.Property<string>("IntersectionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("intersection_id");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Policy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("policy");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("SelectedPhaseId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("selected_phase_id");

                    b.Property<string>("SelectedSignalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("selected_signal_id");

                    b.Property<string>("SelectedSignalIdsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]")
                        .HasColumnName("selected_signal_ids_json");

                    b.Property<int>("YellowDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("yellow_duration_seconds");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("RunId");

                    b.HasIndex("IntersectionId", "IssuedAtUtc");

                    b.ToTable("signal_decision_commands", (string)null);
                });

            modelBuilder.Entity("Traffic.Infrastructure.Persistence.Entities.SignalStateItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ElapsedSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed_seconds");

                    b.Property<int>("QueueLength")
                        .HasColumnType("integer")
                        .HasColumnName("queue_length");

                    b.Property<string>("SignalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("signal_id");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("signal_state_items", (string)null);
                });

            modelBuilder.Entity("Traffic.Infrastructure.Persistence.Entities.SignalStateSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at_utc");

                    b.Property<string>("IntersectionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("intersection_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("RunId");

                    b.HasIndex("IntersectionId", "CapturedAtUtc");

                    b.ToTable("signal_state_snapshots", (string)null);
                });

            modelBuilder.Entity("Traffic.Infrastructure.Persistence.Entities.TrafficMeasurementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Arrivals")
                        .HasColumnType("integer")
                        .HasColumnName("arrivals");

                    b.Property<int>("Departures")
                        .HasColumnType("integer")
                        .HasColumnName("departures");

                    b.Property<string>("IntersectionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("intersection_id");

                    b.Property<DateTimeOffset>("MeasuredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at_utc");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<int>("QueueLength")
                        .HasColumnType("integer")
                        .HasColumnName("queue_length");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("SignalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("signal_id");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("RunId");

                    b.HasIndex("IntersectionId", "SignalId", "MeasuredAtUtc");

                    b.ToTable("traffic_measurements", (string)null);
                });

            modelBuilder.Entity("Traffic.Infrastructure.Persistence.Entities.SignalStateItemEntity", b =>
                {
                    b.HasOne("Traffic.Infrastructure.Persistence.Entities.SignalStateSnapshotEntity", "Snapshot")
                        .WithMany("Signals")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Traffic.Infrastructure.Persistence.Entities.SignalStateSnapshotEntity", b =>
                {
                    b.Navigation("Signals");
                });
#pragma warning restore 612, 618
        }
    }
}
